# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8218efb6ad0ddc1c8821926d58e84424779b4f8e6b127584d09ba5274137b8ab8d4c328528862962ceb2755f576807158b5130d094d3bb2e70dd26feced1cf16

test:
  secret_key_base: a561faa5eb09e6d996a815bda5529214c31b534c3f0c46b9ac5517b05fd4e7ebbe49aac8afe6bb01e83b8690644cd29270ff38be4fb03f9fdf376eb45777d4f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
